language: node_js
node_js: 12.1.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_65b7445359ce_key -iv $encrypted_65b7445359ce_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host ${host}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- CI=false npm run build
after_script:
- ls
after_success:
- ssh $deloy_server "rm -rf ${deloy_root_path}${deloy_path}"
- scp -o stricthostkeychecking=no -r $build_path  "${deloy_server}:${deloy_root_path}${deloy_path}"


